name: "Build documentation"

on:
  push:
    branches:
      - add_ci

jobs:
  build_doc:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    permissions:
      contents: read # to fetch code (actions/checkout)

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
            make libmagic1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Awesome-Binary-Similarity
        uses: actions/checkout@v4
        with:
          repository: SystemSecurityStorm/Awesome-Binary-Similarity
          path: Awesome-Binary-Similarity

      - name: Checkout QBinDiff
        uses: actions/checkout@v4
        with:
          repository: quarkslab/qbindiff
          path: qbindiff

      - name: Checkout python-binexport
        uses: actions/checkout@v4
        with:
          repository: quarkslab/python-binexport
          path: python-binexport

      - name: Checkout idascript
        uses: actions/checkout@v4
        with:
          repository: quarkslab/idascript
          path: idascript

      - name: Checkout python-bindiff
        uses: actions/checkout@v4
        with:
          repository: quarkslab/python-bindiff
          path: python-bindiff

      - name: Checkout quokka
        uses: actions/checkout@v4
        with:
          repository: quarkslab/quokka
          path: quokka

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install Python dependencies"
        run: |
          pip install -r requirements.txt
          pip install enum-tools[sphinx]
          pip install docutils==0.20.1

      - name: "Build Sphinx Doc"
        run: make html

      - uses: actions/upload-artifact@v3
        with:
          name: doc-pages
          path: ./_build/html

  # deploy:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: doc-pages
  #         path: ./doc/_build/html

  #     - name: "Deploy Github Pages"
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         BRANCH: gh-pages
  #         FOLDER: doc/_build/html/
